// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtCHhPzZBaNcPZB4vbwUqal_ieMz928OY',
    appId: '1:1095055850185:android:804c888391e839a76cab18',
    messagingSenderId: '1095055850185',
    projectId: 'event-planning-3c2fd',
    storageBucket: 'event-planning-3c2fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwVSDwF2A-zpso1PWFJsLIWIRgLW15wSU',
    appId: '1:1095055850185:ios:0841c01e07304d0e6cab18',
    messagingSenderId: '1095055850185',
    projectId: 'event-planning-3c2fd',
    storageBucket: 'event-planning-3c2fd.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_3JQFYef4r9yFGtwkEETseLBjPhdDav0',
    appId: '1:1095055850185:web:bcb15d77ad6c35626cab18',
    messagingSenderId: '1095055850185',
    projectId: 'event-planning-3c2fd',
    authDomain: 'event-planning-3c2fd.firebaseapp.com',
    storageBucket: 'event-planning-3c2fd.firebasestorage.app',
    measurementId: 'G-Q89MX6FL33',
  );
}
